name: orderbook-frontend

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push orderbook
        uses: docker/build-push-action@v2
        with:
          context: web/images
          push: true
          tags: muellerp92/orderbook-frontend:latest

      # - name: Build and push orderbook-frontend
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: orderbook/frontend/images
      #     push: true
      #     tags: muellerp92/orderbook-frontend:latest
