name: Build the server app

on:
  push:
    branches: [ master ]
    paths: ['server/**']
  pull_request:
    branches: [ master ]
    paths: ['server/**']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v1.0

      - name: Check code format
        run: cd server && sbt scalafmtCheck

      - name: Compile
        run: cd server && sbt compile && pwd && ls
      
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: orderbook
          path: ./*
